Akinori0123/freemarket_sample_50teama

app/controllers/products_controller.rb
config/routes.rb

・productsのルーティングを設定する
・productsのコントローラを作成する（rails g controller products）
・productsのコントローラにindexアクションを定義する
・products#indexをroot_pathに指定する
products/index（トップページ）のビューを作成するため

productsのルートとコントローラの作成

---

app/assets/stylesheets/_common.scss
app/assets/stylesheets/_reset.scss
app/assets/stylesheets/application.scss

・_reset.scssファイルを作成する
・_reset.scssにYUIを適用する
・_reset.scssをapplication.scssに読み込む
・_common.scssファイルを作成する
・_common.scssをapplication.scssに読み込む
・_common.scssを編集する（事前にせいのさんに作成していただいた内容です）
画面の実装の前に共通で使用するscssファイルを作成するため

リセットcssと共通scssファイルの作成

---

Gemfile
Gemfile.lock

gem unicornの追加、インストール
サーバーでrailsを動かすため

AddUnicornGem

---

Gemfile
Gemfile.lock
config/unicorn.rb
db/schema.rb

unicorn設定ファイルを追加
AWSでrailsを動作させるため

Build deploy configurations

---

config/database.yml

サーバー側のMySQLのrailsへのパスを通す
パス記述の不一致でrailsがMysqlを認識できないため

ChangedMysqlPath

---

config/database.yml

database.ymlのmysql接続設定更新
サーバー環境でのrailsのDB作成

ChangedDatabaseConfigure

---

.gitignore

gitignoreにapp/assets/images/*
を追加することでgitにコミットさせないようにする。
本番環境に必要のないファイルのため

[WIP]gitignoreファイルの編集

---

app/assets/javascripts/items.coffee
app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
test/controllers/items_controller_test.rb

#what
Itemsのコントローラーおよび関連ファイルの作成です。
#why
Productというモデル名ですが、5/6の打ち合わせの結果、itemという名前に変更することになりました。
Items controllerに関するビューも増えてきそうなので、今の段階でコントローラーを生成しておきます。

itemsコントローラーの作成

---

Gemfile
Gemfile.lock

coffee-railsをオフ
上記変更によるgemfile.lockの更新
rails generateなどの時に自動的にcoffeescriptを生成するのを防ぐため

Delete a Gem

---

Gemfile.lock

bundle installせずにマージしてしまいました。
gemfile.lockもマージ願います。

Add ancestry -gemfile.lock

---

app/controllers/application_controller.rb
config/unicorn.rb

masterから消滅していたため再度merge
Basic認証の導入
サーバーでrails起動するため

Unicorn設定ファイルの修復

---

app/assets/stylesheets/_single-wrapper.scss
app/assets/stylesheets/application.scss

single-containerをsingle-wrapperに改名する
名前の記述を間違えていたため

single-containerの名前の修正

---

app/controllers/items_controller.rb
config/routes.rb

itemsコントローラ,new,create actionの追加
上記のルート追加
商品登録ページのviewを作成するため。

itemsコントローラ,new,create actionの追加、左記のルート追加

---

Capfile
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/environments/production.rb
config/unicorn.rb

以下のファイルが今回の操作で生成、記載したものです、**全９ファイル**
サーバーサイドに関しては、これをリモートにmergeしてからが動作確認試験となる流れですので
**①無関係の不要ファイルが混入していないか**
②明らかな全角日本語指示部分の置き換え忘れがないか
記述については②程度で、**①を重視してチェックしていただきたいです。**
Gemfile 
Gemfile.lock
Capfile
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/unicorn.rb
app/controllers/application_controller.rb
config/environments/production.rb
サーバーサイドの機能実装のための設定ファイル群です
自動デプロイはカリキュラム通りのもの、大部分が自動生成による記述。
Basic認証も最終課題要件の支持通りのソースコードの実装となります
その際も特に①に気を払って、**意図しないファイル変更がないこと**だけでも確認いただきたいです。
capistorano⇨一連のデプロイフローを自動化するため
Basic認証⇨開発環境における最低限の認証安全を計るため

自動デプロイ環境用セッティング

---

app/assets/stylesheets/_variables.scss

_variables.scssに@mixin input-default() を追加する
input-boxのスタイルを共有するため

input-box用スタイルの変数化

---

config/deploy/production.rb

一連の設定ファイルの中で、IPアドレスの記入にミスがありました。
現在稼働中のIPアドレスを確認しコピペ。
全ファイルの中で他に同様の記述部分がないことをプロジェクト内サーチして確認、
なので他に同じ記載ミスはない、はず、です。。。
設定ミスを修正し正常稼働させるため

自動デプロイ環境設定の数値修正

---

config/deploy.rb
config/environments/production.rb

・さらに別のIPアドレス記述部分を修正←前回修正の検索の仕方が悪く、今までに数度作り直したIPの一部が検索もれしていました。（config/environments/production.rb
・記述の位置の整理（config/deploy.rb
今後の修正の可能性として一部機能をオフにして検証することが考えられます。
似たような目的の修正確認を数度頼むことになるかもしれません、よろしくお願いします。
・正常に自動デプロイ機能を実装させるため

自動デプロイ設定の修正

---

app/controllers/application_controller.rb
config/environments/production.rb

同時に実装した自動デプロイ機能を一時停止するため
必要な記述２箇所を削除
自動デプロイ機能を実装するため

basic認証機能を一時差し止め

---

config/deploy.rb

不要な記述を削除、動作確認テストを実施します。
config/deploy.rb
・正常なbasic認証を実現するため

デプロイ設定の不要な記述の削除

---

README.md
app/models/card.rb
app/models/category.rb
app/models/image.rb
app/models/item.rb
app/models/like.rb
app/models/user.rb
db/migrate/20190507072718_add_column_to_user.rb
db/migrate/20190507073209_create_items.rb
db/migrate/20190507073228_create_likes.rb
db/migrate/20190507073238_create_cards.rb
db/migrate/20190507073248_create_images.rb
db/migrate/20190507073255_create_categories.rb
db/schema.rb
test/fixtures/cards.yml
test/fixtures/categories.yml
test/fixtures/images.yml
test/fixtures/items.yml
test/fixtures/likes.yml
test/models/card_test.rb
test/models/category_test.rb
test/models/image_test.rb
test/models/item_test.rb
test/models/like_test.rb

必要なモデル・マイグレーションファイルを作成。
(user, item, card, image, category, like)
READMEの転記です。
下記カラムは不必要だったため、README含め変更しました。
userモデルのcardカラム(referencesは子が持つカラム)
itemモデルのseller_idカラム(誰のitemか？の情報は中間テーブルであるlikeが持つ)
データを扱えるようにするため。

モデル・マイグレーションファイル作成

---

app/controllers/application_controller.rb
config/deploy.rb
config/deploy/production.rb

削除した記述をそのまま元に戻して実装
・削除状態でElasticIPのみのアクセスでローカルと同様のviewが表示されることを確認
※空行追加分を削除して戻すファイルが含まれます
ベーシック認証の意図した動作を実現するための検証作業

再度ベーシック認証を実装

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js

JQuery gem の追加
トップ画面にJQueryプラグインを入れたいためです。

Add jquery

---

app/assets/stylesheets/_users.scss
app/views/devise/registrations/new.html.haml

/users/sign_upの画面のマークアップを行う。（link_toのリンク先は全て仮置きで”#”にしています）
・views/devise/registrations/new.html.hamlの編集
・_users.scssの編集
ユーザーの新規登録機能を実装するため

ユーザー新規登録画面のマークアップ

---

app/controllers/application_controller.rb
app/views/users/show.html.haml

app/controllers/application_controller.rb
app/views/users/show.html.haml
開発中サイトに無関係なユーザーがアクセスできないようにする簡易認証機能の実装

Digest認証機能の正常動作を確認できたので実装完了

---

config/environments/production.rb

**本件について調整が続く見込みあり**
デプロイ時にjsのバッククォートがエラーになってそう
記述修正で動作確認
config/environments/production.rb
デプロイエラーの解消

デプロイエラーUglifier::Error: Unexpected character '`'

---

config/environments/production.rb

プリコンパイルは通る状態だが、js使用ページのみwe'reになってしまう
nodejsのharmony機能をfalseしてみる（関係ない可能性大）
jsプリコンパイルエラーを解消し、正常表示させる

修正継続、Uglifier::Error: Unexpected token: operator

---

app/views/shared/_header.html.haml

画像アセットが原因かどうか切り分け検証
エラーログにあった画像を呼び出すimage_tagそのものをオフにして検証
app/views/shared/_header.html.haml
正常なview表示をするため

We'reError画像アセットが原因かどうか切り分け検証

---

app/views/shared/_header.html.haml

image_tagで呼び出す画像をjpgに記載変更、検証
app/views/shared/_header.html.haml
正常なview表示を実現させる

アセット読み込みエラーによるWe're表示解消検証

---

config/environments/production.rb

バグフィックスで使っていた検証用コメントアウトを削除、整理
不要なコメントアウトを削除

アセットコンパイラの記述を整理

---

app/controllers/application_controller.rb

Digest認証機能がローカル開発環境では動作しないよう環境条件での条件分岐を追加
ローカルで動作しなくなったことを確認。
app/controllers/application_controller.rb
ローカル開発操作に不都合があるため。

Digest認証機能動作をサーバー環境のみでの動作に修正

---

app/assets/stylesheets/_users.scss
app/controllers/users_controller.rb
app/views/users/edit.html.haml
app/views/users/mypage/identification.html.haml
config/routes.rb

[メルカリの本人確認ページ](https://www.mercari.com/jp/mypage/identification/)
と同じ見た目になるようにマークアップを行い、本人情報を編集できるようにする。
＊最初の方にコミットした内容を最後のコミットで修正しているので、レビューの際はfiles changedをメインに見ていただけると嬉しいです。
＊不自然なBEM命名、scssの記述、コントローラの記述をレビューしていただけると嬉しいです。
ユーザーの情報を確認&編集できるようにするため。

ユーザー本人確認ページのマークアップ

---

db/seeds.rb

生成されるemailの数字をIDと一致するよう修正
わかりやすくするため

Seedfileの修正

---

config/routes.rb

log/production.log
ActionController::RoutingError (No route matches [GET] "/users"):
ルーティングに問題があるかも？？
resourcesに含まれるルーティングを削除してみる
正常なViewの反映

サーバー表示エラーの解消（トップページ以外が表示されない）

---

app/assets/stylesheets/all/_variables.scss

未定義mixinの呼び出しでエラー
おそらくどこかのマージで消失したため
意図したとおりのviewの実現

消えたmixinの追加修正

---

app/assets/stylesheets/all/_colors.scss

失われたcss変数定義を再実装
意図した通りのviewを実現する

失われたcss変数定義を再実装

---

app/assets/stylesheets/all/_variables.scss

失われたmixinを再実装
意図した通りのviewを実現する

失われたmixinを再実装

---

app/assets/stylesheets/shared/_mypage-tab-container.scss

失われたScssの再実装

---

app/assets/stylesheets/_users.scss
app/controllers/users_controller.rb
app/views/users/edit.html.haml
config/routes.rb

ユーザー本人確認ページを再度表示されるようにする
正常にユーザー本人確認ページが表示されることを確認いたしました。
不要なファイルの編集が無いかをメインにチェックしていただけると嬉しいです。
必須機能のため

ユーザー本人情報確認ページの復活

---

app/models/user_item.rb

サーバーエラーの修正

---

db/seeds.rb

encrypted_passwordを削除
このデータをseedで入れているとpassword不一致でログイン不能のユーザーデータが作成されてしまう
有効なダミーデータを作成するため

Seedファイルの修正

---

app/assets/stylesheets/all/_icons.scss
app/assets/stylesheets/all/_variables.scss

fontawesomeを復活させる
アイコンを表示させるため

fontawesomeの復活

---

app/assets/stylesheets/all/_icons.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/cards/_show-cards.scss
app/assets/stylesheets/items/buy-confirm.scss
app/assets/stylesheets/users/_logout.scss
app/controllers/cards_controller.rb
app/views/cards/show.html.haml
app/views/items/confirm.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_footer_sell_btn.html.haml
config/routes.rb
test/controllers/cards_controller_test.rb

Reverts Akinori0123/freemarket_sample_50teama#103

Revert "Revert "クレジットカード一覧表示ページ""

---

app/assets/stylesheets/all/_icons.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/cards/_show-cards.scss
app/assets/stylesheets/items/buy-confirm.scss
app/assets/stylesheets/users/_logout.scss
app/controllers/cards_controller.rb
app/views/cards/show.html.haml
app/views/items/confirm.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_footer_sell_btn.html.haml
config/routes.rb
test/controllers/cards_controller_test.rb

Reverts Akinori0123/freemarket_sample_50teama#110

Revert "Revert "Revert "Revert "クレジットカード一覧表示ページ""""

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb

以下の３つのgemの実装です
（development, test環境）
gem 'pry-rails'
gem 'pry-byebug'
gem 'pry-doc'
デバッグ作業をスムーズに行うためです。
余計なファイルがないことをご確認ください。

binding pry 関連gemのインストール

---

README.md
db/migrate/20190519033615_add_column_detail_to_item.rb
db/migrate/20190519040956_add_column_ship_from_to_item.rb
db/schema.rb

itemモデルに
ship_from 発送元地域
detail 商品説明
上記2カラムを追加。
また、READMEの更新
item詳細ページ、登録ページに必要なため。

データベース変更(Addcolumn ship_from & detail to Item)

---

README.md
db/migrate/20190519043956_add_column_ship_by_to_item.rb
db/schema.rb
db/seeds.rb

ship_from | integer | null: false | 発送元地域
-- | -- | -- | --
ship_by | integer | null: false | 発送方法
に追加変更しました。
また、seedも変更したのでマージしたら
rake db:reset
rake db:seed
をおこなってほしいぞ！
商品登録に必要なため。

Itemカラム変更 & null false制約追加によるseedの変更

---

app/assets/stylesheets/all/_variables.scss
app/assets/stylesheets/users/_logout.scss

・新規登録時、カード情報入力画面でfontawesomeが適応されていなかったのを修正
・ログアウト画面で、ログアウトのリンクをボタン全体に拡大
ユーザー関連のscssを本家に近づけるため

user関連のscssの修正

---

Gemfile
Gemfile.lock
spec/controllers/items_controller_spec.rb
spec/factories/items.rb

・rails-controller-testing（gem）を追加
・商品一覧表示機能（items#index）のテスト
正常に商品一覧が表示されていることを確認するため

商品一覧表示機能のテスト

---

app/assets/stylesheets/cards/show-cards.scss
app/views/cards/show.html.haml

カード表示ページの崩れていたビューの修正です
見た目を整えるためです
・当該ページのビューの崩れがないことを確認しました。
・修正の結果、同じレイアウトをしている、
users/mypage/logout
users/mypage/profile 
でも崩れがないことを確認しました。
[![Image from Gyazo](https://i.gyazo.com/ad68f9df77f9911fd7c5a034c86bdec7.gif)](https://gyazo.com/ad68f9df77f9911fd7c5a034c86bdec7)

カード表示ページのビューの修正

---

app/assets/stylesheets/cards-create.scss
app/assets/stylesheets/cards/show-cards.scss
app/assets/stylesheets/items/_main-footer.scss
app/assets/stylesheets/items/_main-header.scss
app/views/cards/new.html.haml
app/views/cards/show.html.haml
app/views/items/index.html.haml
app/views/items/new.html.haml
app/views/shared/_footer-sell-btn.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_footer_sell_btn.html.haml
app/views/shared/_header.html.haml
app/views/shared/_items-box.html.haml
app/views/shared/_mypage-nav.html.haml

各ページのリンクを作成しました。
また、随所で小さいscssの修正を行いました。
他にも修正箇所がありますが、長くなりそうなので一旦レビューしていただけると嬉しいです。
各ページの行き来を簡単にするため

リンクの追加とscssの修正

---

app/controllers/items_controller.rb

新しいitemがsaveされたときに、中間テーブルに値が保存されるようにする
誰の商品か判別できるようにするため

商品出品機能の中間テーブルの修正

---

app/assets/stylesheets/items/_item-box.scss
app/assets/stylesheets/items/show-detail.scss
app/views/items/show.html.haml
app/views/shared/_items-box.html.haml

itemのstatusが2(売り切れ状態)の場合にSOLDを表示させる
視覚的に売り切れ状態を把握できるようにするため

販売済みitemにSOLD表示

---

app/assets/javascripts/category.js
app/assets/stylesheets/items/_new.scss
app/controllers/application_controller.rb
app/controllers/cards_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/new.html.haml

商品出品時に、カテゴリを選択できるようにする
＊各commitのdescriptionに、そのcommitで何をしているか記載しました
商品に任意のカテゴリーを持たせられるようにするため

商品出品時にカテゴリー選択機能

---

app/assets/javascripts/category.js
app/assets/stylesheets/items/_item-box.scss
app/assets/stylesheets/items/search-page.scss
app/controllers/categories_controller.rb
app/views/categories/show.html.haml
app/views/shared/_category-list.html.haml
app/views/shared/_header.html.haml
config/breadcrumbs.rb
config/routes.rb

ヘッダーのカテゴリー一覧から、カテゴリーごとの商品一覧を見られるようにする
＊commitのdescriptionに、各commitで何をしたか記載しております
カテゴリーによる絞り込みを行えるようにするため

カテゴリーごとの商品一覧画面の追加

---

app/assets/javascripts/items-new.js
app/controllers/items_controller.rb
app/views/items/new.html.haml
app/views/users/show.html.haml

商品出品、マイページのhaml,controllerを微修正
商品出品ページのjsを追加
＊各commitのdescriptionに変更内容を記述しています。
使いやすくするため

ユーザー出品ページの微修正

---

Gemfile
Gemfile.lock
app/controllers/cards_controller.rb
app/controllers/items_controller.rb
app/models/item.rb
config/routes.rb
spec/controllers/cards_controller_spec.rb
spec/factories/categories.rb
spec/factories/items.rb
spec/factories/users.rb
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/controller_macros.rb

cards controllerの単体TEST
file changed の詳細はcommitに記載。
実行結果
[![Image from Gyazo](https://i.gyazo.com/76f38c607e0910b286c19a6148f79ea9.png)](https://gyazo.com/76f38c607e0910b286c19a6148f79ea9)
プログラムが意図した通りに動くことを確かめるため。

TEST cards_controller

---

spec/controllers/items_controller_spec.rb

items_controller showアクションのテスト
プログラムが意図した通りに動くことを確かめるため。
[![Image from Gyazo](https://i.gyazo.com/3c833bb0e0125d29e32e4f112b7fb8f6.png)](https://gyazo.com/3c833bb0e0125d29e32e4f112b7fb8f6)

TEST items_controller #show

---

app/assets/stylesheets/items/buy-confirm.scss
app/views/items/confirm.html.haml

購入確認画面の画像表示。
また、paddingの修正。
何を購入するのか、確認がわかりやすくするため。

購入確認画面の画像表示

---

spec/controllers/users_controller_spec.rb
spec/features/users_spec.rb

以下のテストを行う。
・各ユーザー登録ページにアクセスできるか
・新規ユーザー登録できるか
・ログインできるか
正常にユーザ機能が動作しているかテストするため

ユーザー登録のテスト

---

app/assets/javascripts/item-box.js
app/assets/javascripts/mordal-window.js
app/assets/stylesheets/items/_item-box.scss
app/assets/stylesheets/shared/item-box-small.scss
app/views/shared/_items-box.html.haml

アイテムボックスの見た目の不具合の修正です
タイトルの文字量が多いアイテム→「…」と表示
タイトル末尾にグラデーション
見た目の改善のためです
[![Image from Gyazo](https://i.gyazo.com/dff18416db3604b2b76b6819089bce31.gif)](https://gyazo.com/dff18416db3604b2b76b6819089bce31)

アイテムボックスの修正

---

app/controllers/items_controller.rb

クレジットカード情報がない場合のエラー修正
default_cardがない場合は redirect_to items_path
操作性向上のため。

クレジットカード情報がない場合のエラー修正

---

app/assets/stylesheets/items/_item-box.scss
app/assets/stylesheets/items/show-detail.scss

soldのz-index変更
categoryがsoldに潜ってしまうため。

z-indexの変更
