- db/schema.rb
rake db:migrateの実行されていないスキーマファイルを実行後のものに上書き
各メンバーのローカル環境でコンフリクトの原因になってしまうため
> マイグレーションファイルとスキーマ内容齟齬の解消

- .gitignore
coffee, secrets.ymlを追記
自動生成された使われないファイルを本番環境に入れないため
サーバーアクセスキー等機密情報を一般公開させないため
> Gitignoreの追記

- Gemfile
ツリー構造を簡単に作れるgemを導入します。
現在は3世代のみですが、構造が深くなった時にルーティングを変える手間が省けるため。
> Add ancestry

- app/assets/stylesheets/_colors.scss
- app/assets/stylesheets/application.scss
共通のCSSの中にあった不具合を修正しました。その結果、
*= require_tree .
を削除しました。
CSSを読み込む順番が制御できずエラーがで続けていたためです。
詳細を確認されたい場合、下記をご覧ください。
https://railsguides.jp/asset_pipeline.html#%E3%83%9E%E3%83%8B%E3%83%95%E3%82%A7%E3%82%B9%E3%83%88%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A8%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96
> cssの不具合の修正

- app/controllers/application_controller.rb
- config/environments/production.rb
追加したBasic認証機能を取り外すためメソッドを削除
デプロイ環境開発の都合上、前回のプルリクで追加した記述をいったん削除してますので
他に操作してないことを確認していただきたいです。
サーバー環境構築の適正化
> サーバー環境でのBasic認証機能導入の一時停止

- app/controllers/application_controller.rb
- config/environments/production.rb
自動デプロイ機能そのものの動作は確認が取れたので
ベーシック認証機能を追加させてサーバーサイドの稼働を検証します。
※再度追加削除で機能検証する可能性があります。
開発中サーバーアプリへの簡易アクセス制限をするため
> ベーシック認証機能の追加

- config/deploy/production.rb
- config/environments/production.rb
記述するべきファイルが間違っていたため修正
・開発中サーバーアプリに最低限の認証機能を備えて開発チームだけがアクセスできるようにするため。
> Basic認証機能ファイル修正

- app/controllers/application_controller.rb
- config/deploy.rb
- config/deploy/production.rb
サーバー環境検証用に追加したベーシック認証機能を一時的にオフにします
※このプルリクの少し前にしたリモートリポジトリとローカルのファイル差異確認をした時の空行追加が含まれています。
ベーシック認証機能の確認のため
> ベーシック認証機能を一時オフにします

- app/controllers/application_controller.rb
- config/deploy/production.rb
ベーシック認証機能を取り外し、一旦別の機能の実装に取り掛かります。
・他の機能実装を進めるため。
> ベーシック認証機能の解除

- config/environments/production.rb
前回デプロイ自体は成功したものの、jsを持ちいいているトップページのみがwe'reエラー状態になったため修正を模索。
config/environments/production.rb
ローカル状態を反映できるデプロイ環境を構築するため
> デプロイエラー修正継続、Uglifier::Error: Unexpected character '`' 

- app/controllers/items_controller.rb
- app/views/items/_items-box.html.haml
トップページに出品された商品の一覧を表示する。
・items_controllerに@itemsを定義
・_items-box.html.hamlを編集
＊商品詳細へのリンク、いいね数、商品画像は仮置きのままです。
トップページから商品にアクセスできるようにするため。
> 商品一覧表示機能の実装

- .gitignore
gitignoreにpublic/myfilesを追加
pushしたくないが、個人的に退避させておきたソースコードなどを
このフォルダ以下にファイル作成して保管してください。
プロジェクト内に個人用ソースとマージ用ソースを共存管理させるため
> 各自の個人的なソース退避用フォルダの作成

- app/controllers/users_controller.rb
- app/models/concerns/valid_columns.rb
- app/models/user.rb
- app/views/devise/sessions/new.html.haml
- app/views/shared/_single-footer.html.haml
- app/views/shared/_single-header.html.haml
- app/views/users/new.html.haml
- app/views/users/signup/address.html.haml
- app/views/users/signup/card.html.haml
- app/views/users/signup/complete.html.haml
- app/views/users/signup/registration.html.haml
- config/routes.rb
ユーザー新規登録をウィザードフォームにて行えるようにする。
＊レビュワーの方へ
申し訳ありません、昨日[こちらのプルリクエスト](https://github.com/Akinori0123/freemarket_sample_50teama/pull/81)にて同じ作業をしていましたが、masterへの不要な変更が`git revert`を用いても打ち消すことができず、またコンフリクトも大量に発生してしまったため、作業効率を考えて新しいプルリクエストを作らせていただきました。
昨日いただいたレビューと、その返信は以下の通りです。
レビュー内容を反映させた修正はcorrect-hamlコミットとcorrect-routeコミットの二つです。ご確認のほどよろしくお願いいたします。
ユーザー機能を実装するため。
> ユーザー新規登録（ウィザードフォーム）

- db/migrate/20190518033611_add_omniauth_to_users.rb
- db/schema.rb
userモデルに以下のカラムを追加する
・string型のproviderカラム（facebook,google認証のため）
・string型のuidカラム（facebook,google認証のため）
・string型のpayjp_idカラム（payjpのため）
> userモデルにfacebook認証とpayjpのためのカラムを追加

- db/schema.rb
- db/seeds.rb
UserItemテーブルのダミー追加
既存ダミーデータのUserと出品Itemのデータを結びつけて利用できるようにするため
> UserItemテーブルのダミー追加

- Gemfile.lock
payjpによるgemfile.lockを解除
payjpのbundleインストール時にエラーを起こしている。
ローカルでbundle install 作成されたgemfile.lockによる縛りを解除して
サーバでのpayjpインストールを試してみる
> サーバーデプロイエラー対処

- Gemfile.lock
自分のローカルで生成したgemfile.lockをアップロードしてみる
実質的に前回の対処前に変更を戻すだけ
https://github.com/Akinori0123/freemarket_sample_50teama/pull/135
でのgemfile.lock変更と特に変わりないことを確認済。
おそらくこの変更によってエラー解決することはないと予測。
デプロイプロセスのbundle install時のエラーが継続しているが
bundle installしてからgemfile.lock作ってアップロードしろ的なことを言われているため。
また現在の状態のままでいるとpullした時に必ずgemfile.lockを各ローカルで変更することになり
pushファイルに含まれてしまうため。
> サーバーデプロイエラー対処中

- app/models/item.rb
- config/locales/ja.yml
**本件についてローカルでエラー解消、viewの表示を確認。**
**一連のフォーム上でユーザー登録完了し、そのレコード作成を確認。**
新規ユーザー登録画面で以下のエラー
[undefined method `map' for "translation missing: ja.date.order":String]
config/locales/ja.yml
当該エラーはja: date: order:であるが、
以下の記事を参考に関係の近い部分を一式取り入れている。
https://qiita.com/wada811/items/e26692ca3dea4e03ba30
本件の日本語変換の元となるenumのフォームでの数値の扱いをわかりやすくするため。
本エラーと直接の因果関係はないが、将来的な開発しやすさ、バグの発生を防ぐ目的での変更。
app/models/item.rb
config/locals/以下にある特定のymlファイルは
ざっくりいうとrailsで使われる特定のシンボルに対する対応文字列の辞書みたいなもの。
おそらく
gem enum_helpの追加に伴って、ja.ymlを参照するように設定したのだが、
rails既存機能のうちen.ymlの辞書を参照して動作していた機能までもが
その設定情報のもとja.ymlを参照するようになった。
しかし、参照するべき辞書がja.yml内に存在しない事でエラーとなっていたと考えられる。
そもそもこのja.yml追加時点でローカル動作からレコード作成まで確認していたのに
なぜ今になって若干関係ない部分でこのエラーが出てきたのかは不明。
つまり、本件の周辺範囲でのエラー解消は確認できたものの、
(あまり頻繁な例とは考えにくいが)今後他の新たなrailsヘルパーメソッドを利用した場合などに、 …
> 新規ユーザー登録画面のエラー解消

- app/models/user.rb
[#130](https://github.com/Akinori0123/freemarket_sample_50teama/pull/130)により消えたuserモデルのself.from_omniauthメソッドを復活させる
SNSアカウントによるログインを可能にするため
> SNSアカウントによる新規登録・ログイン機能の復活

- .gitignore
- app/models/item.rb
app/models/item.rb
.gitignore
※carrierwaveのアップロード先設定により、従前のseedを実行すると
新たにpublic/uploads/以下にアップロードされた画像ファイルが作成されます。
そもそも各環境においてcarrierwaveでのアップロードを経由した画像seedを作るには
アップローダの指定をするヘルパーメソッドの記述が必要、この点で
チームの各ローカルと、商品新規登録フォームでの動作試験をしていた端末では原因が別でした。
mout_uploaders :image, ItemUploader
というように、ヘルパーメソッドが間違った複数形をしていた
あるいはヘルパーメソッドそのものがなかったということで、carrierwaveアップローダが正常に動作できない環境にあった。
ただし、ここではヘルパーメソッドそのものが未定義、
というようなエラーはなかったことから、この記述そのものがおかしい、あるいは
記述そのものがないことでseedのopen()メソッドがエラーを起こして止まるわけではない様子。
何れにしても、単数形複数形には厳格な意味があるので、コピペソースに含まれている場合かなり注意するべき項目である。
> アップローダ修正（追記）

- app/models/image.rb
- app/models/item.rb
**画像アップロードするモデルにヘルパーメソッドが必要。**
app/models/item.rb
残っていても目立った問題はないが、不要な機能を実行できる記述は出来るだけ削除。
app/models/image.rb
ヘルパーメソッド追記するべきモデルを間違えていた修正
> #152アップローダ修正の修正

- app/models/item.rb
- app/views/items/confirm.html.haml
- app/views/items/show.html.haml
カラム名編集によるview_enum崩れの解消
SSIA
https://blog.sixapart.jp/2016-10/lgtm-github.html
表示確認済みです。
カラムを変更したことでviewが開けない。enumが適切に表示させられないバグの解消
> カラム名編集によるview_enum崩れの解消

- app/assets/stylesheets/shared/_mypage-nav.scss
- app/views/shared/_items-box.html.haml
- app/views/shared/_mypage-nav.html.haml
各コミットで、以下の修正を行いました
・mypage-navのリンクをprefixで記述
・mypage-navのリンクの範囲をボタン全体に広げる
・item-boxのリンクの範囲が画像のみだったのをitem-box全体に広げる
リンクボタンをクリックしやすくするようにするため
> リンクとリンクボタンのscssの修正

- db/migrate/20190524043027_add_column_status_to_item.rb
- db/schema.rb
- db/seeds.rb
Itemモデルにstatusカラムの追加。(defailt値は1)
カラム変更に伴うseedファイルの更新。
補足
localでmigrate済み。
出品者が出品状況を判断できるようにするため。
出品状況によってuserに公開するitemsをソートするため。
> 出品状態 カラムの追加

- app/assets/javascripts/carousel.js
- app/assets/stylesheets/carousel/slick-theme.scss
- app/assets/stylesheets/items/show-detail.scss
- app/views/items/index.html.haml
- app/views/items/show.html.haml
- app/views/shared/_items-box.html.haml
商品詳細ページのカルーセルの実装です
画像表示はまだ全ページで表示されない状況なので、引き続きの検討事項とします
見た目を改善するためです。
特に、プラグインのコンテンツである、デフォルトのcssの扱い方について（変更して良いものなのか、プラグインがマークアップにStyleを書き込む仕組みになっていたため、!importantを多用して修正せざるを得なかった）など教えいていただけますと幸いです。
app/assets/javascripts/carousel.js カルーセルの動作
app/assets/stylesheets/carousel/slick-theme.scss slickのデフォルトのcss
app/assets/stylesheets/items/show-detail.scss 商品詳細ページのcss
app/views/items/index.html.haml スライダー加工のためのクラス名追記
app/views/items/show.html.haml　マークアップ変更
app/views/shared/_items-box.html.haml 小さいタイプのitem box用に書き換え
↑すみません、最後の１ファイルは、前に作業していたブランチでの変更内容ですが、うまくプッシュされていなかったようですので、ここにくわえさせてください。
▼動作確認用GIF
[![Image from Gyazo](https://i.gyazo.com/69bce1ff63a037c1091bad25abba5a66.gif)](https://gyazo.com/69bce1ff63a037c1091bad25abba5a66)
> 商品詳細ページカルーセルの実装

- app/controllers/items_controller.rb
- app/views/items/new.html.haml
- db/seeds.rb
出品ページの:category_idsを:category_idに修正
itemsのストロングパラメータにcategory_idを追加
seedファイルを微修正（caetgory_idが0のitemが作られないようにする）
**現在ブランドの欄に数字でカテゴリーidを打ち込まないと出品できません**
**itemsテーブルにないサイズとブランドをどうするか要相談**
商品出品ページにアクセスできるようにするため。
> 商品出品ページにアクセスできないエラーの解消

- app/controllers/items_controller.rb
- app/views/items/confirm.html.haml
- app/views/items/show.html.haml
- config/application.rb
- config/locales/ja.yml
app/controllers/items_controller.rb
これにより、
商品詳細 => 購入画面に進む => 購入する
の動作でエラーなく表示されることを確認
app/views/items/confirm.html.haml
app/views/items/show.html.haml
**以後同様のことがしたい場合、enumの名前_i18n**
**で日本語文字列化させることができます。**
i18nってなんぞと思ったらi (nternationalizatio) n
()が18文字っていう、単なる国際標準化の短縮表現だった。
config/application.rb
config/locales/ja.yml
正直、これで完全に大丈夫かというとわからないので
今後ja.ymlに起因するエラーが発生した場合には再度修正検討対象
諸々発生したバグフィックス
> enum設定変更、enum呼び出し関数の修正、routeing変更でのsetメソッド修正対応

- app/controllers/items_controller.rb
- app/views/items/show.html.haml
- app/views/shared/_items-box.html.haml
app/views/shared/_items-box.html.haml
seedカテゴリがランダムなため写真とカテゴリは合ってません
app/views/items/show.html.haml
他プルリクで出してますが、ついでにenumシンボルの日本語文字列化をさせてます。
app/controllers/items_controller.rb
私の現在のrandではレディースstatus=1がゼロだったためレディース表示は消えました。
sliderによるサムネが５枚までしか表示されません
eachで全て出してるはずなのでレイアウト上の制限がかかってる？
DBから画像を表示させる
<a href="https://gyazo.com/f5bba444c026fe368b7fb102d7e754d5"><img src="https://i.gyazo.com/f5bba444c026fe368b7fb102d7e754d5.gif" alt="Image from Gyazo" width="776"/></a>
> 画像パスの修正、トップページレコードのセレクトステータス

- app/assets/stylesheets/items/buy-confirm.scss
- app/assets/stylesheets/items/show-detail.scss
- app/views/items/show.html.haml
商品詳細ページの編集
・商品のカテゴリにリンクを追加
・画面幅を小さくした時に画面外に要素が飛び出していたのを修正
・未ログイン時で画面幅を小さくすると上の購入ボタンに空の吹き出しが表示されるのを修正
・購入ボタンのリンクをボタン全体に広げる
購入確認ページの編集
・画面幅を小さくした時に画面外に要素が飛び出していたのを修正
画面幅が小さい場合でも閲覧しやすくするため
> 商品詳細ページと購入確認ページのレスポンシブ化

- app/views/items/show.html.haml
購入済みのアイテムの表示の設定（soldボタン、売り切れの商品は削除も編集もできないようにする、など）
ユーザーに不便がないようにです。
[![Image from Gyazo](https://i.gyazo.com/2144889bdaf6b93c46cdbfc1ace05f1e.png)](https://gyazo.com/2144889bdaf6b93c46cdbfc1ace05f1e)
> 購入済みのアイテムの表示設定

- app/assets/javascripts/item-box.js
- app/assets/stylesheets/items/_item-box.scss
- app/views/shared/_items-box.html.haml
item/indexページにおいて、item-boxの数が、
最大幅＝＞４個
タブレットサイズ＝＞３個
スマホサイズ＝＞４個
表示されるようにしました。
画像の表示を本来のサイトに近づけるためです。
画像の縦横比固定はWIPでお願いいたします
[![Image from Gyazo](https://i.gyazo.com/0dd7694a11a24e5dc691e25c6efe54b7.gif)](https://gyazo.com/0dd7694a11a24e5dc691e25c6efe54b7)
> item-boxのcss修正

- app/views/shared/_footer.html.haml
- app/views/shared/_mypage-nav.html.haml
- app/views/users/mypage/identification.html.haml
- app/views/users/mypage/logout.html.haml
- app/views/users/mypage/profile.html.haml
- app/views/users/show.html.haml
各ページにrenderとして切り分けられていたが、footerにも記載があったため、footerのあるページ全てに表示されていた。
footerのrenderを削除。
・items
index / search
・users
show / identification / logout /prifile
・categories
show
・cards
index / new
・items
show / confirm / new / edit
・users
new / signup
出品することに重きをおくために基本出品ボタンは出ているが、
買う意識になっている場合(商品詳細や購入確認ページ)には非表示にすることで意識のノイズを消す。
> 右下出品ボタンをページによって非表示にする

- app/controllers/categories_controller.rb
- app/controllers/items_controller.rb
・トップページで商品一覧を表示する際、子孫カテゴリの商品も表示
・カテゴリ詳細で商品一覧を表示する際、子孫カテゴリの商品も表示
カテゴリによる絞り込みを容易にするため
> カテゴリー表示の修正

- app/controllers/items_controller.rb
- app/views/items/show.html.haml
・同じuserの商品一覧を表示
・同じカテゴリの商品一覧に、子孫カテゴリの商品も表示
ユーザが出品したその他の商品を確認するため
> 商品詳細ページのその他の商品一覧表示の修正

- app/assets/javascripts/mordal-window.js
- app/controllers/items_controller.rb
- app/views/items/search.html.haml
- app/views/items/show.html.haml
- spec/controllers/items_controller_spec.rb
items_controller searchアクションのテストです。
ついでに、items_controllerの動きが想定どおりでなかった箇所を修正しました
（検索に一致する結果がなかった時に、新着アイテムが表示されるようにする）
必須の項目だからです。
"%#{params[:keyword]}%"を含む@itemのテストについては、今回は諦めることにしました
[![Image from Gyazo](https://i.gyazo.com/8b8d08805ad6340dcab9654dcce73313.png)](https://gyazo.com/8b8d08805ad6340dcab9654dcce73313)
[![Image from Gyazo](https://i.gyazo.com/b551b650244bec7528b40afc021b81a4.gif)](https://gyazo.com/b551b650244bec7528b40afc021b81a4)
> items_controller(searchアクション)のテスト,items_controllerの不具合修正
